### ISSUE TITLE
一旦使用223.5.5.5软件就无法启动

### ISSUE THREAD

**Issue by Mijjj** [pymumu/smartdns#57]
**问题现象**
简要描述问题出现的现象
一旦使用223.5.5.5软件就无法启动
**运行环境**
1. 固件型号
树莓派
2. 运营商
联通/校园网
**重现步骤**
1. 上游DNS配置。
server 8.8.8.8
server 1.2.4.8
server 114.114.114.114
server 119.29.29.29
server 1.1.1.1
server 117.50.11.11
#server 223.5.5.5.5
server-tcp 8.8.8.8
server-tcp 1.2.4.8
server-tcp 114.114.114.114
server-tcp 119.29.29.29
server-tcp 1.1.1.1
server-tcp 117.50.11.11
#server-tcp 223.5.5.5.5

2. 访问的域名。
所有

**信息收集**
1. 将/var/log/smrtdns.log日志作为附件上传。
2. 如可能，将coredump功能开启，上传coredump信息文件。
在自定义界面，开启设置->自定义设置->生成coredump配置，重现问题后提交coredump文件
coredump文件在/tmp目录下

**Comment by Mijjj** [comment]
`pi@raspberrypi:~ $ sudo systemctl status smartdns
● smartdns.service - smart dns server
   Loaded: loaded (/lib/systemd/system/smartdns.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-01-06 04:24:33 CST; 893ms ago
  Process: 23714 ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 23715 (code=exited, status=1/FAILURE)

1月 06 04:24:33 raspberrypi systemd[1]: smartdns.service: Main process exited, code=exited, status=1/FAILURE
1月 06 04:24:33 raspberrypi systemd[1]: smartdns.service: Unit entered failed state.
1月 06 04:24:33 raspberrypi systemd[1]: smartdns.service: Failed with result 'exit-code'.
`

**Comment by pymumu** [comment]
你IP地址写错了吧，有4个5，应该只有3个5吧。

**Comment by Liqianyu** [comment]
TCP查询现已经大范围Reset。EDNS目前还不会被污染。
@pymumu SmartDNS自带反污染效果？必须用blacklist-ip list吧？

**Comment by pymumu** [comment]
看情况，国外dns能访问的话，udp模式启用反应答污染功能就好了，速度还快。一般电信，联通用8.8.8.8都可以，这个功能可以过滤抢答结果，使用正确的结果。

移动8.8.8.8是假的，请求不会到真正的8.8.8.8，所以这个反应答污染功能对移动8.8.8.8无用，看dns是否假的，可以看ping值，ping在10ms以下肯定是假的服务器，这样的服务器不行

防污染效果最好是tls，8.8.8.8，1.1.1.1都支持tls了，端口是853，缺点是响应慢点。可以尝试

ip黑名单主要针对国内公共dns，将投毒的ip地址加到列表里面，有投毒ip的结果会直接丢弃。在配合tls的话，就可以获取正确结果同时得到最快结果，ip黑名单支持子网。

但要注意一点，这些功能只能保证结果正确，无法避免查询信息泄露。如果要避免信息泄露，配置国外dns+tls即可

**Comment by samondlee** [comment]
> 看情况，国外dns能访问的话，udp模式启用反应答污染功能就好了，速度还快。一般电信，联通用8.8.8.8都可以，这个功能可以过滤抢答结果，使用正确的结果。
> 
> 移动8.8.8.8是假的，请求不会到真正的8.8.8.8，所以这个反应答污染功能对移动8.8.8.8无用，看dns是否假的，可以看ping值，ping在10ms以下肯定是假的服务器，这样的服务器不行
> 
> 防污染效果最好是tls，8.8.8.8，1.1.1.1都支持tls了，端口是853，缺点是响应慢点。可以尝试
> 
> ip黑名单主要针对国内公共dns，将投毒的ip地址加到列表里面，有投毒ip的结果会直接丢弃。在配合tls的话，就可以获取正确结果同时得到最快结果，ip黑名单支持子网。
> 
> 但要注意一点，这些功能只能保证结果正确，无法避免查询信息泄露。如果要避免信息泄露，配置国外dns+tls即可

呜呜呜 大佬 最好给个配置例子呀~


集成到 软件里

**Comment by samondlee** [comment]
> 看情况，国外dns能访问的话，udp模式启用反应答污染功能就好了，速度还快。一般电信，联通用8.8.8.8都可以，这个功能可以过滤抢答结果，使用正确的结果。
> 
> 移动8.8.8.8是假的，请求不会到真正的8.8.8.8，所以这个反应答污染功能对移动8.8.8.8无用，看dns是否假的，可以看ping值，ping在10ms以下肯定是假的服务器，这样的服务器不行
> 
> 防污染效果最好是tls，8.8.8.8，1.1.1.1都支持tls了，端口是853，缺点是响应慢点。可以尝试
> 
> ip黑名单主要针对国内公共dns，将投毒的ip地址加到列表里面，有投毒ip的结果会直接丢弃。在配合tls的话，就可以获取正确结果同时得到最快结果，ip黑名单支持子网。
> 
> 但要注意一点，这些功能只能保证结果正确，无法避免查询信息泄露。如果要避免信息泄露，配置国外dns+tls即可

大佬怎么添加IPV6 DNS地址呀

server 2001:da8::666 这样写对不对QAQ

**Comment by samondlee** [comment]
> 看情况，国外dns能访问的话，udp模式启用反应答污染功能就好了，速度还快。一般电信，联通用8.8.8.8都可以，这个功能可以过滤抢答结果，使用正确的结果。
> 
> 移动8.8.8.8是假的，请求不会到真正的8.8.8.8，所以这个反应答污染功能对移动8.8.8.8无用，看dns是否假的，可以看ping值，ping在10ms以下肯定是假的服务器，这样的服务器不行
> 
> 防污染效果最好是tls，8.8.8.8，1.1.1.1都支持tls了，端口是853，缺点是响应慢点。可以尝试
> 
> ip黑名单主要针对国内公共dns，将投毒的ip地址加到列表里面，有投毒ip的结果会直接丢弃。在配合tls的话，就可以获取正确结果同时得到最快结果，ip黑名单支持子网。
> 
> 但要注意一点，这些功能只能保证结果正确，无法避免查询信息泄露。如果要避免信息泄露，配置国外dns+tls即可

dalao N1 ARMBIAN 用树莓派版本无法启动为啥呀



root@aml:~# systemctl enable smartdns
Created symlink /etc/systemd/system/smartdns.service → /lib/systemd/system/smartdns.service.
Created symlink /etc/systemd/system/multi-user.target.wants/smartdns.service → /lib/systemd/system/smartdns.service.
root@aml:~# systemctl start smartdns
Job for smartdns.service failed because the control process exited with error code.
See "systemctl status smartdns.service" and "journalctl -xe" for details.
root@aml:~# systemctl start smartdns
Job for smartdns.service failed because the control process exited with error code.
See "systemctl status smartdns.service" and "journalctl -xe" for details.

**Comment by samondlee** [comment]
-- 
-- The result is failed.
Jan 14 14:08:58 aml systemd[1]: smartdns.service: Unit entered failed state.
Jan 14 14:08:58 aml systemd[1]: smartdns.service: Failed with result 'exit-code'.
lines 3942-3948/3948 (END)
-- Support: https://www.debian.org/support
-- 
-- Unit smartdns.service has failed.
-- 
-- The result is failed.
Jan 14 14:08:58 aml systemd[1]: smartdns.service: Unit entered failed state.
Jan 14 14:08:58 aml systemd[1]: smartdns.service: Failed with result 'exit-code'.
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 3942-3948/3948 (END)

**Comment by samondlee** [comment]
● smartdns.service - smart dns server
   Loaded: loaded (/lib/systemd/system/smartdns.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-01-14 14:09:54 UTC; 1s ago
  Process: 15982 ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS (code=exited, status=203/EXEC)

Jan 14 14:09:54 aml systemd[1]: smartdns.service: Unit entered failed state.
Jan 14 14:09:54 aml systemd[1]: smartdns.service: Failed with result 'exit-code'.
root@aml:~#

**Comment by pymumu** [comment]
armbian的运行时和raspbian的不同。

要用armbian的编译环境才行。但我现在只有树莓派，没有N1

只能看后面有机会再增加二进制了。

**Comment by pymumu** [comment]
armbian的后面有编译环境会提供。
